version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'highlight.js'
    groups:
      dev-dependencies:
        patterns:
          - '*'
