version: 2
jobs:
  build:
    docker:
      - image: node:9
    working_directory: ~/uikit-site
    steps:
      - run:
          name: Update Environment
          command: apt-get update && apt-get -y install rsync
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Dependencies
          command: |
            yarn install --pure-lockfile --cache-folder ~/.yarn
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn
            - ./node_modules
      - run:
          name: Compile
          command: |
            mkdir css
            yarn run compile
      - run:
          name: Replace Build Number
          command: |
            sed -i -- "s/{{BUILD}}/$CIRCLE_BUILD_NUM/g" index.html
            sed -i -- "s/{{BUILD}}/$CIRCLE_BUILD_NUM/g" docs/index.html
      - run:
          name: Replace relative paths
          command: |
            sed -i -- 's/href="[^http]/href="https:\/\/getuikit.com\//g' index.html
            sed -i -- 's/href="[^http]/href="https:\/\/getuikit.com\/docs\//g' docs/index.html
            sed -i -- 's/src="[^http]/src="https:\/\/getuikit.com\//g' index.html
            sed -i -- 's/src="[^http]/src="https:\/\/getuikit.com\/docs\//g' docs/index.html
      - run:
          name: Transfer Files
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ];then
              rsync -avze "ssh -o StrictHostKeyChecking=no" --exclude-from ".circleci/exclude.txt" --copy-links --delete . $UIKIT_SERVER
            else
              echo "Skipping deploy on branch ${CIRCLE_BRANCH}";
            fi
